git:
  depth: 3

language: cpp

compiler:
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

    - os: osx
      osx_image: xcode7.3
      sudo: required

addons:
  apt:
    packages:
      - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install clang; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update; fi

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
